export const REQUEST_REQUEST = 'ECARD_REQUEST_REQUEST';
export const REQUEST_SUCCESS = 'ECARD_REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'ECARD_REQUEST_FAILURE';
export const REQUEST_RESET = 'ECARD_REQUEST_RESET';
