export const QUERY_PARKING_INFO_REQUEST = 'QUERY_PARKING_INFO_REQUEST';
export const QUERY_PARKING_INFO_SUCCESS = 'QUERY_PARKING_INFO_SUCCESS';
export const QUERY_PARKING_INFO_FAILURE = 'QUERY_PARKING_INFO_FAILURE';

export const QUERY_PARKING_MY_HISTORY_REQUEST = 'QUERY_PARKING_MY_HISTORY_REQUEST';
export const QUERY_PARKING_MY_HISTORY_SUCCESS = 'QUERY_PARKING_MY_HISTORY_SUCCESS';
export const QUERY_PARKING_MY_HISTORY_FAILURE = 'QUERY_PARKING_MY_HISTORY_FAILURE';

export const MODIFY_PARKING_AUTH_REQUEST = 'MODIFY_PARKING_AUTH_REQUEST';
export const MODIFY_PARKING_AUTH_SUCCESS = 'MODIFY_PARKING_AUTH_SUCCESS';
export const MODIFY_PARKING_AUTH_FAILURE = 'MODIFY_PARKING_AUTH_FAILURE';
