export const FETCH_CONTENTS_REQUEST = 'FETCH_CONTENTS_REQUEST';
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS';
export const FETCH_CONTENTS_FAILURE = 'FETCH_CONTENTS_FAILURE';

export const FETCH_CONTENTS_BY_PATH_REQUEST = 'FETCH_CONTENTS_BY_PATH_REQUEST';
export const FETCH_CONTENTS_BY_PATH_SUCCESS = 'FETCH_CONTENTS_BY_PATH_SUCCESS';
export const FETCH_CONTENTS_BY_PATH_FAILURE = 'FETCH_CONTENTS_BY_PATH_FAILURE';

export const SEARCH_COMPANIES_REQUEST = 'SEARCH_COMPANIES_REQUEST';
export const SEARCH_COMPANIES_SUCCESS = 'SEARCH_COMPANIES_SUCCESS';
export const SEARCH_COMPANIES_FAILURE = 'SEARCH_COMPANIES_FAILURE';

export const CONTENTS_COMMENT_REQUEST = 'CONTENTS_COMMENT_REQUEST';
export const CONTENTS_COMMENT_SUCCESS = 'CONTENTS_COMMENT_SUCCESS';
export const CONTENTS_COMMENT_FAILURE = 'CONTENTS_COMMENT_FAILURE';

export const CONTENTS_UNIFY_REQUEST = 'CONTENTS_UNIFY_REQUEST';
export const CONTENTS_UNIFY_SUCCESS = 'CONTENTS_UNIFY_SUCCESS';
export const CONTENTS_UNIFY_FAILURE = 'CONTENTS_UNIFY_FAILURE';

export const RESET_CONTENTS = 'RESET_CONTENTS';
