export const ECARD_RECHARGE = 'ECARD_RECHARGE';
export const ECARD_RESET_RECHARGE = 'ECARD_RESET_RECHARGE';

export const BILL_RECORD_REQUEST = 'BILL_RECORD_REQUEST';
export const BILL_RECORD_SUCCESS = 'BILL_RECORD_SUCCESS';
export const BILL_RECORD_FAILURE = 'BILL_RECORD_FAILURE';
