//Ticket list
export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';

export const ADD_TICKET_REQUEST = 'ADD_TICKET_REQUEST';
export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const ADD_TICKET_FAILURE = 'ADD_TICKET_FAILURE';

export const RESET_TICKET = 'RESET_TICKET';

export const FETCH_TICKET_TEMPLATE_REQUEST = 'FETCH_TICKET_TEMPLATE_REQUEST';
export const FETCH_TICKET_TEMPLATE_SUCCESS = 'FETCH_TICKET_TEMPLATE_SUCCESS';
export const FETCH_TICKET_TEMPLATE_FAILURE = 'FETCH_TICKET_TEMPLATE_FAILURE';

export const FETCH_TICKET_REQUEST = 'FETCH_TICKET_REQUEST';
export const FETCH_TICKET_SUCCESS = 'FETCH_TICKET_SUCCESS';
export const FETCH_TICKET_FAILURE = 'FETCH_TICKET_FAILURE';
