export const TOKEN_LOGIN_REQUEST = 'TOKEN_LOGIN_REQUEST';
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS';
export const TOKEN_LOGIN_FAILURE = 'TOKEN_LOGIN_FAILURE';

export const SEND_CODE_REQUEST = 'AUTH_SEND_CODE_REQUEST';
export const SEND_CODE_SUCCESS = 'AUTH_SEND_CODE_SUCCESS';
export const SEND_CODE_FAILURE = 'AUTH_SEND_CODE_FAILURE';

export const VERIFY_CODE_REQUEST = 'AUTH_VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'AUTH_VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'AUTH_VERIFY_CODE_FAILURE';

export const CERTIFICATION_REQUEST = 'CERTIFICATION_REQUEST';
export const CERTIFICATION_SUCCESS = 'CERTIFICATION_SUCCESS';
export const CERTIFICATION_FAILURE = 'CERTIFICATION_FAILURE';
export const CERTIFICATION_RESET = 'CERTIFICATION_RESET';
