//Building list
export const FETCH_BUILDINGS_REQUEST = 'FETCH_BUILDINGS_REQUEST';
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS';
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE';
