export const FETCH_METERS_REQUEST = 'FETCH_METERS_REQUEST';
export const FETCH_METERS_SUCCESS = 'FETCH_METERS_SUCCESS';
export const FETCH_METERS_FAILURE = 'FETCH_METERS_FAILURE';

export const FETCH_METER_REQUEST = 'FETCH_METER_REQUEST';
export const FETCH_METER_SUCCESS = 'FETCH_METER_SUCCESS';
export const FETCH_METER_FAILURE = 'FETCH_METER_FAILURE';

export const CONFIRM_METER_READING_REQUEST = 'CONFIRM_METER_READING_REQUEST';
export const CONFIRM_METER_READING_SUCCESS = 'CONFIRM_METER_READING_SUCCESS';
export const CONFIRM_METER_READING_FAILURE = 'CONFIRM_METER_READING_FAILURE';
