const config = require('../config');
const logger = require('../lib/logging').getLogger('lib/export_xlsx');

const xlsxTemplate = require('xlsx-template');
const fs = require('fs');
const path = require('path');
const _ = require('lodash');
const moment = require('moment');

const mdb = require('../mongoose');

//读模板
function readFileP(template_path) {
  return fs.readFileSync(template_path);
}
//写文件
function writeFileP(filename, newData) {
  fs.writeFileSync(path.join(config.print_outputs, `${filename}.xlsx`), newData, 'binary');
}
//
// 打印租户入住搬家审批表
//
exports.printTicketTemplate = async (ticket) => {
  const form_data = ticket.form_data;
  const ticket_template = ticket.ticket_template;

  const filename = [ticket_template.excel_file, moment().format('YYYYMMDDhhmmss')].join('-');
  const template_path = path.join(__dirname, '..', 'public', config.views.excels, `${ticket_template.excel_file}.xlsx`);
  const data = await readFileP(template_path);
  const t = new xlsxTemplate(data);

  if (ticket_template._id === 'settle_in' || ticket_template._id === 'settle_out') {
    t.substitute(1, {
      settle_in_unit_name: form_data.settle_in_unit_name,
      settle_in_floor: form_data.settle_in_floor,
      settle_in_number: form_data.settle_in_number,
      settle_in_service_type: form_data.settle_in_service_type === '确认',
      settle_in_service_commitment: form_data.settle_in_service_commitment === '确认',
      settle_in_service_sheet: form_data.settle_in_service_sheet === '确认',
      settle_in_service_template: form_data.settle_in_service_template === '确认',
      settle_in_project_acceptance: form_data.settle_in_project_acceptance === '确认',
      settle_in_project_drawing: form_data.settle_in_project_drawing === '确认',
      settle_in_project_other: form_data.settle_in_project_other,
      settle_in_security_submissions_1: form_data.settle_in_security_submissions === '确认',
      settle_in_security_submissions_2: form_data.settle_in_security_submissions === '无需取得',
      settle_in_security_security: form_data.settle_in_security_security === '确认',
      settle_in_security_fire_apparatus: form_data.settle_in_security_fire_apparatus === '确认',
      settle_in_security_other: form_data.settle_in_security_other,
      settle_in_service_manager: form_data.settle_in_service_manager,
      settle_in_service_manager_year: moment(form_data.settle_in_service_manager_date).year(),
      settle_in_service_manager_month: moment(form_data.settle_in_service_manager_date).month() + 1,
      settle_in_service_manager_date: moment(form_data.settle_in_service_manager_date).date(),
      settle_in_project_manager: form_data.settle_in_project_manager,
      settle_in_project_manager_year: moment(form_data.settle_in_project_manager_date).year(),
      settle_in_project_manager_month: moment(form_data.settle_in_project_manager_date).month() + 1,
      settle_in_project_manager_date: moment(form_data.settle_in_project_manager_date).date(),
      settle_in_security_manager: form_data.settle_in_project_manager,
      settle_in_security_manager_year: moment(form_data.settle_in_security_manager_date).year(),
      settle_in_security_manager_month: moment(form_data.settle_in_security_manager_date).month() + 1,
      settle_in_security_manager_date: moment(form_data.settle_in_security_manager_date).date(),
      settle_in_general_manager: form_data.settle_in_general_manager,
      settle_in_general_manager_year: moment(form_data.settle_in_general_manager_date).year(),
      settle_in_general_manager_month: moment(form_data.settle_in_general_manager_date).month() + 1,
      settle_in_general_manager_date: moment(form_data.ettle_in_general_manager_date).date(),
    });
  } else if (ticket_template._id === 'completed_acceptance_check') {
    t.substitute(1, {
      completed_acceptance_checks_type_1: form_data.completed_acceptance_checks_type === '租户装修',
      completed_acceptance_checks_type_2: form_data.completed_acceptance_checks_type === '项目委托施工',
      completed_acceptance_checks_type_3: form_data.completed_acceptance_checks_type === '外部单位项目内施工',
      completed_acceptance_checks_floor: form_data.completed_acceptance_checks_floor,
      completed_acceptance_checks_number: form_data.completed_acceptance_checks_number,
      completed_acceptance_checks_area: form_data.completed_acceptance_checks_area,
      completed_acceptance_checks_tenantry_unit_name: form_data.completed_acceptance_checks_tenantry_unit_name,
      completed_acceptance_checks_tenantry_contact: form_data.completed_acceptance_checks_tenantry_contact,
      completed_acceptance_checks_tenantry_tel: form_data.completed_acceptance_checks_tenantry_tel,
      completed_acceptance_checks_construction_unit_name: form_data.completed_acceptance_checks_construction_unit_name,
      completed_acceptance_checks_construction_contact: form_data.completed_acceptance_checks_construction_contact,
      completed_acceptance_checks_construction_tel: form_data.completed_acceptance_checks_construction_tel,
      completed_acceptance_checks_result_1: form_data.completed_acceptance_checks_result === '验收合格',
      completed_acceptance_checks_result_2: form_data.completed_acceptance_checks_result === '待整改后复验',
      completed_acceptance_checks_rectification_items: form_data.completed_acceptance_checks_rectification_items,
      completed_acceptance_checks_department_manager: form_data.completed_acceptance_checks_chief_manager,
      completed_acceptance_checks_project_manager: form_data.completed_acceptance_checks_repair_manager,
      completed_acceptance_checks_security_manager: form_data.completed_acceptance_checks_security_manager,
      completed_acceptance_checks_retest_result: form_data.completed_acceptance_checks_retest_result === '验收合格',
      completed_acceptance_checks_retest_department_manager: form_data.completed_acceptance_checks_retest_chief_manager,
      completed_acceptance_checks_retest_project_manager: form_data.completed_acceptance_checks_retest_repair_manager,
      completed_acceptance_checks_retest_security_manager: form_data.completed_acceptance_checks_retest_security_manager,
    });
  } else if (ticket_template._id === 'decoration_application') {
    t.substitute(1, {
      decoration_application_type_1: form_data.decoration_application_type === '租户装修',
      decoration_application_type_2: form_data.decoration_application_type === '项目委托施工',
      decoration_application_type_3: form_data.decoration_application_type === '外部单位项目内施工',
      decoration_application_floor: form_data.decoration_application_floor,
      decoration_application_number: form_data.decoration_application_number,
      decoration_application_area: form_data.decoration_application_area,
      decoration_application_tenantry_unit_name: form_data.decoration_application_tenantry_unit_name,
      decoration_application_tenantry_contact: form_data.decoration_application_tenantry_contact,
      decoration_application_tenantry_tel: form_data.decoration_application_tenantry_tel,
      decoration_application_construction_unit_name: form_data.decoration_application_construction_unit_name,
      decoration_application_construction_contact: form_data.decoration_application_construction_contact,
      decoration_application_construction_tel: form_data.decoration_application_construction_tel,
      decoration_application_plan_drawing_year: moment(form_data.decoration_application_plan_drawing_date_time).year(),
      decoration_application_plan_drawing_month: moment(form_data.decoration_application_plan_drawing_date_time).month() + 1,
      decoration_application_plan_drawing_date: moment(form_data.decoration_application_plan_drawing_date_time).date(),
      decoration_application_plan_drawing_hour: moment(form_data.decoration_application_plan_drawing_date_time).hour(),
      decoration_application_plan_repair_approved_1: form_data.decoration_application_plan_repair_approved === '同意进入后续流程',
      decoration_application_plan_repair_approved_2: form_data.decoration_application_plan_repair_approved === '修改后再报审',
      decoration_application_plan_repair_approved_manager: form_data.decoration_application_plan_repair_approved_manager,
      decoration_application_plan_security_approved_1: form_data.decoration_application_plan_security_approved === '同意进入后续流程',
      decoration_application_plan_security_approved_2: form_data.decoration_application_plan_security_approved === '修改后再报审',
      decoration_application_plan_security_approved_manager: form_data.decoration_application_plan_security_approved_manager,
      decoration_application_plan_building_approved_1: form_data.decoration_application_plan_building_approved === '同意进入后续流程',
      decoration_application_plan_building_approved_2: form_data.decoration_application_plan_building_approved === '修改后再报审',
      decoration_application_plan_building_approved_manager: form_data.decoration_application_plan_building_approved_manager,
    });

    t.substitute(2, {
      decoration_application_type_1: form_data.decoration_application_type === '租户装修',
      decoration_application_type_2: form_data.decoration_application_type === '项目委托施工',
      decoration_application_type_3: form_data.decoration_application_type === '外部单位项目内施工',
      decoration_application_floor: form_data.decoration_application_floor,
      decoration_application_number: form_data.decoration_application_number,
      decoration_application_area: form_data.decoration_application_area,
      decoration_application_tenantry_unit_name: form_data.decoration_application_tenantry_unit_name,
      decoration_application_tenantry_contact: form_data.decoration_application_tenantry_contact,
      decoration_application_tenantry_tel: form_data.decoration_application_tenantry_tel,
      decoration_application_construction_unit_name: form_data.decoration_application_construction_unit_name,
      decoration_application_construction_contact: form_data.decoration_application_construction_contact,
      decoration_application_construction_tel: form_data.decoration_application_construction_tel,
      decoration_application_license_year: moment(form_data.decoration_application_license_date_time).year(),
      decoration_application_license_month: moment(form_data.decoration_application_license_date_time).month() + 1,
      decoration_application_license_date: moment(form_data.decoration_application_license_date_time).date(),
      decoration_application_license_hour: moment(form_data.decoration_application_license_date_time).hour(),
      decoration_application_license_receipt: form_data.decoration_application_license_receipt === '确认',
      decoration_application_license_opinion: form_data.decoration_application_plan_repair_approved === '确认',
      decoration_application_license_responsible_manager: form_data.decoration_application_license_responsible_manager,
      decoration_application_fire_receipt: form_data.decoration_application_fire_receipt === '确认',
      decoration_application_no_need_fire_file: form_data.decoration_application_no_need_fire_file === '需要',
      decoration_application_license_security_manager: form_data.decoration_application_license_security_manager,
      decoration_application_license_repair_manager: form_data.decoration_application_license_repair_manager,
      decoration_application_license_chief_manager: form_data.decoration_application_license_chief_manager,
    });

    t.substitute(3, {
      decoration_application_type_1: form_data.decoration_application_type === '租户装修',
      decoration_application_type_2: form_data.decoration_application_type === '项目委托施工',
      decoration_application_type_3: form_data.decoration_application_type === '外部单位项目内施工',
      decoration_application_floor: form_data.decoration_application_floor,
      decoration_application_number: form_data.decoration_application_number,
      decoration_application_area: form_data.decoration_application_area,
      decoration_application_tenantry_unit_name: form_data.decoration_application_tenantry_unit_name,
      decoration_application_license_from_year: moment(form_data.decoration_application_license_from_date).year(),
      decoration_application_license_from_month: moment(form_data.decoration_application_license_from_date).month() + 1,
      decoration_application_license_from_date: moment(form_data.decoration_application_license_from_date).date(),
      decoration_application_license_end_year: moment(form_data.decoration_application_license_end_date).year(),
      decoration_application_license_end_month: moment(form_data.decoration_application_license_end_date).month() + 1,
      decoration_application_license_end_date: moment(form_data.decoration_application_license_end_date).date(),
      decoration_application_license_issue_year: moment(form_data.decoration_application_license_issue_date).year(),
      decoration_application_license_issue_month: moment(form_data.decoration_application_license_issue_date).month() + 1,
      decoration_application_license_issue_date: moment(form_data.decoration_application_license_issue_date).date(),
    });
  } else if (ticket_template._id === 'goods_letin' || ticket_template._id === 'goods_letout') {
    t.substitute(1, {
      goods_let_company_name: form_data.goods_let_unit_name,
      goods_let_floor: form_data.goods_let_floor,
      goods_let_number: form_data.goods_let_number,
      goods_let_type_1: form_data.goods_let_type === '搬入',
      goods_let_type_2: form_data.goods_let_type === '搬出',
      goods_let_unloading_channel_1: form_data.goods_let_unloading_channel === '是',
      goods_let_unloading_channel_2: form_data.goods_let_unloading_channel === '否',
      goods_let_cement: form_data.goods_let_cement,
      goods_let_board: form_data.goods_let_board,
      goods_let_metal: form_data.goods_let_metal,
      goods_let_desk: form_data.goods_let_desk,
      goods_let_wood: form_data.goods_let_wood,
      goods_let_computer: form_data.goods_let_computer,
      goods_let_projector: form_data.goods_let_projector,
      goods_let_tv: form_data.goods_let_tv,
      goods_let_fan: form_data.goods_let_fan,
      goods_let_seal: form_data.goods_let_seal,
      goods_let_vegetation: form_data.goods_let_vegetation,
      goods_let_water: form_data.goods_let_water,
      goods_let_applicant: form_data.goods_let_applicant,
      goods_let_applicant_appertain: form_data.goods_let_applicant_appertain,
      goods_let_confirm_staff: form_data.goods_let_building_staff,
      goods_let_building_staff: form_data.goods_let_building_staff,
    });
  } else if (ticket_template._id === 'hide_acceptance_check') {
    t.substitute(1, {
      hide_acceptance_check_type_1: form_data.hide_acceptance_check_type === '租户装修',
      hide_acceptance_check_type_2: form_data.hide_acceptance_check_type === '项目委托施工',
      hide_acceptance_check_type_3: form_data.hide_acceptance_check_type === '外部单位项目内施工',
      hide_acceptance_check_floor: form_data.hide_acceptance_check_floor,
      hide_acceptance_check_number: form_data.hide_acceptance_check_number,
      hide_acceptance_check_area: form_data.hide_acceptance_check_area,
      hide_acceptance_check_tenantry_unit_name: form_data.hide_acceptance_check_tenantry_unit_name,
      hide_acceptance_check_tenantry_contact: form_data.hide_acceptance_check_tenantry_contact,
      hide_acceptance_check_tenantry_tel: form_data.hide_acceptance_check_tenantry_tel,
      hide_acceptance_check_construction_unit_name: form_data.hide_acceptance_check_construction_unit_name,
      hide_acceptance_check_construction_contact: form_data.hide_acceptance_check_construction_contact,
      hide_acceptance_check_construction_tel: form_data.hide_acceptance_check_construction_tel,
      hide_acceptance_check_content: form_data.hide_acceptance_check_content,
      hide_acceptance_check_result_1: form_data.hide_acceptance_check_result === '验收合格',
      hide_acceptance_check_result_2: form_data.hide_acceptance_check_result === '待整改后复验',
      hide_acceptance_check_repair_manager: form_data.hide_acceptance_check_repair_manager,
      hide_acceptance_check_repair_year: moment(form_data.hide_acceptance_check_repair_date).year(),
      hide_acceptance_check_repair_month: moment(form_data.hide_acceptance_check_repair_date).month() + 1,
      hide_acceptance_check_repair_date: moment(form_data.hide_acceptance_check_repair_date).date(),
      hide_acceptance_check_retest_result_1: form_data.hide_acceptance_check_retest_result === '验收合格',
      hide_acceptance_check_retest_result_2: form_data.hide_acceptance_check_retest_result === '待整改后复验',
      hide_acceptance_check_retest_repair_manager: form_data.hide_acceptance_check_retest_repair_manager,
      hide_acceptance_check_retest_repair_year: moment(form_data.hide_acceptance_check_retest_repair_date).year(),
      hide_acceptance_check_retest_repair_month: moment(form_data.hide_acceptance_check_retest_repair_date).month() + 1,
      hide_acceptance_check_retest_repair_date: moment(form_data.hide_acceptance_check_retest_repair_date).date(),
    });
  } else if (ticket_template._id === 'office_handover') {
    t.substitute(1, {
      office_handover_type_1: form_data.office_handover_type === '入',
      office_handover_type_2: form_data.office_handover_type === '退',
      office_handover_doors_unit: form_data.office_handover_doors_unit,
      office_handover_doors_number: form_data.office_handover_doors_number,
      office_handover_doors_compliance: form_data.office_handover_doors_compliance,
      office_handover_doors_memo: form_data.office_handover_doors_memo,
      office_handover_window_unit: form_data.office_handover_window_unit,
      office_handover_window_number: form_data.office_handover_window_number,
      office_handover_window_compliance: form_data.office_handover_window_compliance,
      office_handover_window_memo: form_data.office_handover_window_memo,
      office_handover_windowsill_unit: form_data.office_handover_windowsill_unit,
      office_handover_windowsill_number: form_data.office_handover_windowsill_number,
      office_handover_windowsill_compliance: form_data.office_handover_windowsill_compliance,
      office_handover_windowsill_memo: form_data.office_handover_windowsill_memo,
      office_handover_bearing_wall_unit: form_data.office_handover_bearing_wall_unit,
      office_handover_bearing_wall_number: form_data.office_handover_bearing_wall_number,
      office_handover_bearing_wall_compliance: form_data.office_handover_bearing_wall_compliance,
      office_handover_bearing_wall_memo: form_data.office_handover_bearing_wall_memo,
      office_handover_wall_unit: form_data.office_handover_wall_unit,
      office_handover_wall_number: form_data.office_handover_wall_number,
      office_handover_wall_compliance: form_data.office_handover_wall_compliance,
      office_handover_wall_memo: form_data.office_handover_wall_memo,
      office_handover_ceiling_unit: form_data.office_handover_ceiling_unit,
      office_handover_ceiling_number: form_data.office_handover_ceiling_number,
      office_handover_ceiling_compliance: form_data.office_handover_ceiling_compliance,
      office_handover_ceiling_memo: form_data.office_handover_ceiling_memo,
      office_handover_ground_unit: form_data.office_handover_ground_unit,
      office_handover_ground_number: form_data.office_handover_ground_number,
      office_handover_ground_compliance: form_data.office_handover_ground_compliance,
      office_handover_ground_memo: form_data.office_handover_ground_memo,
      office_handover_fence_unit: form_data.office_handover_fence_unit,
      office_handover_fence_number: form_data.office_handover_fence_number,
      office_handover_fence_compliance: form_data.office_handover_fence_compliance,
      office_handover_fence_memo: form_data.office_handover_fence_memo,
      office_handover_outlet_unit: form_data.office_handover_outlet_unit,
      office_handover_outlet_number: form_data.office_handover_outlet_number,
      office_handover_outlet_compliance: form_data.office_handover_outlet_compliance,
      office_handover_outlet_memo: form_data.office_handover_outlet_memo,
      office_handover_inlet_unit: form_data.office_handover_inlet_unit,
      office_handover_inlet_number: form_data.office_handover_inlet_number,
      office_handover_inlet_compliance: form_data.office_handover_inlet_compliance,
      office_handover_inlet_memo: form_data.office_handover_inlet_memo,
      office_handover_controller_unit: form_data.office_handover_controller_unit,
      office_handover_controller_number: form_data.office_handover_controller_number,
      office_handover_controller_compliance: form_data.office_handover_controller_compliance,
      office_handover_controller_memo: form_data.office_handover_controller_memo,
      office_handover_nozzle_unit: form_data.office_handover_nozzle_unit,
      office_handover_nozzle_number: form_data.office_handover_nozzle_number,
      office_handover_nozzle_compliance: form_data.office_handover_nozzle_compliance,
      office_handover_nozzle_memo: form_data.office_handover_nozzle_memo,
      office_handover_hydrant_unit: form_data.office_handover_hydrant_unit,
      office_handover_hydrant_number: form_data.office_handover_hydrant_number,
      office_handover_hydrant_compliance: form_data.office_handover_hydrant_compliance,
      office_handover_hydrant_memo: form_data.office_handover_hydrant_memo,
      office_handover_radio_unit: form_data.office_handover_radio_unit,
      office_handover_radio_number: form_data.office_handover_radio_number,
      office_handover_radio_compliance: form_data.office_handover_radio_compliance,
      office_handover_radio_memo: form_data.office_handover_radio_memo,
      office_handover_sensor_unit: form_data.office_handover_sensor_unit,
      office_handover_sensor_number: form_data.office_handover_sensor_number,
      office_handover_sensor_compliance: form_data.office_handover_sensor_compliance,
      office_handover_sensor_memo: form_data.office_handover_sensor_memo,
      office_handover_exhaust_unit: form_data.office_handover_exhaust_unit,
      office_handover_exhaust_number: form_data.office_handover_exhaust_number,
      office_handover_exhaust_compliance: form_data.office_handover_exhaust_compliance,
      office_handover_exhaust_memo: form_data.office_handover_exhaust_memo,
      office_handover_indicator_unit: form_data.office_handover_indicator_unit,
      office_handover_indicator_number: form_data.office_handover_indicator_number,
      office_handover_indicator_compliance: form_data.office_handover_indicator_compliance,
      office_handover_indicator_memo: form_data.office_handover_indicator_memo,
      office_handover_lamp_unit: form_data.office_handover_lamp_unit,
      office_handover_lamp_number: form_data.office_handover_lamp_number,
      office_handover_lamp_compliance: form_data.office_handover_lamp_compliance,
      office_handover_lamp_memo: form_data.office_handover_lamp_memo,
      office_handover_switch_unit: form_data.office_handover_switch_unit,
      office_handover_switch_number: form_data.office_handover_switch_number,
      office_handover_switch_compliance: form_data.office_handover_switch_compliance,
      office_handover_switch_memo: form_data.office_handover_switch_memo,
      office_handover_socket_unit: form_data.office_handover_socket_unit,
      office_handover_socket_number: form_data.office_handover_socket_number,
      office_handover_socket_compliance: form_data.office_handover_socket_compliance,
      office_handover_socket_memo: form_data.office_handover_socket_memo,
      office_handover_distribution_unit: form_data.office_handover_distribution_unit,
      office_handover_distribution_number: form_data.office_handover_distribution_number,
      office_handover_distribution_compliance: form_data.office_handover_distribution_compliance,
      office_handover_distribution_memo: form_data.office_handover_distribution_memo,
      office_handover_junction_unit: form_data.office_handover_junction_unit,
      office_handover_junction_number: form_data.office_handover_junction_number,
      office_handover_junction_compliance: form_data.office_handover_junction_compliance,
      office_handover_junction_memo: form_data.office_handover_junction_memo,
      office_handover_water_meter_unit: form_data.office_handover_water_meter_unit,
      office_handover_water_meter_number: form_data.office_handover_water_meter_number,
      office_handover_water_meter_compliance: form_data.office_handover_water_meter_compliance,
      office_handover_water_meter_memo: form_data.office_handover_water_meter_memo,
      office_handover_ammeter_unit: form_data.office_handover_ammeter_unit,
      office_handover_ammeter_number: form_data.office_handover_ammeter_number,
      office_handover_ammeter_compliance: form_data.office_handover_ammeter_compliance,
      office_handover_ammeter_memo: form_data.office_handover_ammeter_memo,
      office_handover_key_unit: form_data.office_handover_key_unit,
      office_handover_key_number: form_data.office_handover_key_number,
      office_handover_key_compliance: form_data.office_handover_key_compliance,
      office_handover_key_memo: form_data.office_handover_key_memo,
      office_handover_memo: form_data.office_handover_memo,
      office_handover_building_manager: form_data.office_handover_building_manager,
      office_handover_repair_manager: form_data.office_handover_repair_manager,
      office_handover_security_manager: form_data.office_handover_security_manager,
      office_handover_tenantry: form_data.office_handover_tenantry,
    });
  } else if (ticket_template._id === 'deposit_refund') {
    t.substitute(1, {
      deposit_refund_type_1: form_data.deposit_refund_type === '租户装修',
      deposit_refund_type_2: form_data.deposit_refund_type === '项目委托施工',
      deposit_refund_type_3: form_data.deposit_refund_type === '外部单位项目内施工',
      deposit_refund_floor: form_data.deposit_refund_floor,
      deposit_refund_number: form_data.deposit_refund_number,
      deposit_refund_area: form_data.deposit_refund_area,
      deposit_refund_tenantry_unit_name: form_data.deposit_refund_tenantry_unit_name,
      deposit_refund_tenantry_contact: form_data.deposit_refund_tenantry_contact,
      deposit_refund_tenantry_tel: form_data.deposit_refund_tenantry_tel,
      deposit_refund_afford_expense_1: form_data.deposit_refund_afford_expense === '施工单位',
      deposit_refund_afford_expense_2: form_data.deposit_refund_afford_expense === '租户',
      deposit_refund_afford_expense_3: form_data.deposit_refund_afford_expense === '项目部',
      deposit_refund_afford_expense_approved: form_data.deposit_refund_afford_expense_approved,
      deposit_refund_construction_unit_name: form_data.deposit_refund_construction_unit_name,
      deposit_refund_construction_contact: form_data.deposit_refund_construction_contact,
      deposit_refund_construction_tel: form_data.deposit_refund_construction_tel,
      deposit_refund_repair_approved: form_data.deposit_refund_repair_approved === '确认',
      deposit_refund_drawing_approved_1: form_data.deposit_refund_drawing_approved_1 === '确认',
      deposit_refund_remove_approved: form_data.deposit_refund_remove_approved === '确认',
      deposit_refund_periphery_approved: form_data.deposit_refund_periphery_approved === '确认',
      deposit_refund_repair_approved_manager: form_data.deposit_refund_repair_approved_manager,
      deposit_refund_repair_approved_year: moment(form_data.deposit_refund_repair_approved_date).year(),
      deposit_refund_repair_approved_month: moment(form_data.deposit_refund_repair_approved_date).month() + 1,
      deposit_refund_repair_approved_date: moment(form_data.deposit_refund_repair_approved_date).date(),
      deposit_refund_drawing_approved_2: form_data.deposit_refund_drawing_approved_2 === '确认',
      deposit_refund_fire_approved: form_data.deposit_refund_fire_approved === '确认',
      deposit_refund_security_approved_manager: form_data.deposit_refund_security_approved_manager,
      deposit_refund_security_approved_year: moment(form_data.deposit_refund_security_approved_date).year(),
      deposit_refund_security_approved_month: moment(form_data.deposit_refund_security_approved_date).month() + 1,
      deposit_refund_security_approved_date: moment(form_data.deposit_refund_security_approved_date).date(),
      deposit_refund_card_approved: form_data.deposit_refund_card_approved === '确认',
      deposit_refund_contaminated_approved: form_data.deposit_refund_contaminated_approved === '确认',
      deposit_refund_building_approved_manager: form_data.deposit_refund_building_approved_manager,
      deposit_refund_building_approved_year: moment(form_data.deposit_refund_building_approved_date).year(),
      deposit_refund_building_approved_month: moment(form_data.deposit_refund_building_approved_date).month() + 1,
      deposit_refund_building_approved_date: moment(form_data.deposit_refund_building_approved_date).date(),
      deposit_amount: form_data.deposit_amount,
      deposit_return_amount: form_data.deposit_return_amount,
      deposit_amount_memo: form_data.deposit_amount_memo,
      card_amount: form_data.card_amount,
      card_return_amount: form_data.card_return_amount,
      electricity_fee_amount: form_data.electricity_fee_amount,
      electricity_fee_return_amount: form_data.electricity_fee_return_amount,
      electricity_fee_amount_memo: form_data.electricity_fee_amount_memo,
      drainage_fee_amount: form_data.drainage_fee_amount,
      drainage_fee_return_amount: form_data.drainage_fee_return_amount,
      drainage_fee_amount_memo: form_data.drainage_fee_amount_memo,
      amercement_amount: form_data.amercement_amount,
      amercement_return_amount: form_data.amercement_return_amount,
      amercement_amount_memo: form_data.amercement_amount_memo,
      repair_fee_amount: form_data.repair_fee_amount,
      repair_fee_return_amount: form_data.repair_fee_return_amount,
      repair_fee_amount_memo: form_data.repair_fee_amount_memo,
      total_amount: form_data.total_amount,
      total_amount_memo: form_data.total_amount_memo,
      deposit_refund_repair_manager: form_data.deposit_refund_repair_manager,
      deposit_refund_security_manager: form_data.deposit_refund_security_manager,
      deposit_refund_building_manager: form_data.deposit_refund_building_manager,
      deposit_refund_finace_staff: form_data.deposit_refund_fee_confirmer,
      deposit_refund_chief_manager: form_data.deposit_refund_chief_manager,
    });
  }

  //新文件名
  const newData = t.generate();
  await writeFileP(filename, newData);
  return `${filename}.xlsx`;
};
